CREATE TABLE patients (
  id TEXT PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  gender TEXT,
  date_of_birth DATE,
  marital_status TEXT,
  nationality TEXT,
  registered_facility TEXT,
  emergency_contact TEXT,
  blood_type TEXT,
  mobile_number TEXT,
  last_visit TIMESTAMP,
  registered_date TIMESTAMP,
  photo BINARY,
  address_1 TEXT,
  address_2 TEXT,
  city TEXT,
  state TEXT,
  country TEXT,
  postal_code TEXT,
  referral_id TEXT,
  physician_id TEXT,
  vip BOOLEAN,
  last_updated TIMESTAMP
);